Adding PanoramaWeb Dashboard module
LabKey/MacCossLabModules pull request #37
Opened 2020-03-25 16:55 UTC by vagisha

Contains queries and code to render PanoramaWeb usage charts.  
Creating PR against the right base branch!

2020-03-25 21:49 UTC, labkey-jeckels requested changes
I haven't tried running the code to test the behavior for myself, but what's the expectation in terms of what data should be shown to what users? I'm unsure what permission checks and/or filtering are required here, if any.

2020-03-25 21:49 UTC, labkey-jeckels commented on dashboard/src/org/labkey/dashboard/FolderDocsTable.java
> +        setName("FolderDocs");
Can you create a constant for this name and use it in the schema class too?

2020-03-25 21:49 UTC, labkey-jeckels commented on dashboard/module.properties
> +Label: PanoramaWeb Dashboard
Please flag this module as Postgres only, since I don't see any need for SQLServer support and that will limit the need to test on both DBs

2020-03-25 21:49 UTC, labkey-jeckels commented on dashboard/src/org/labkey/dashboard/ProjectAdminsTable.java
> +            return new StringBuilder().append("<a href='").append(url.getLocalURIString()).append("'>").append(member.getName()).append("</a>").toString();
Need to HTML-encode the name. Consider using our new-ish org.labkey.api.util.DOM builder utility

2020-03-25 21:49 UTC, labkey-jeckels commented on dashboard/module.properties
> +ModuleDependencies: TargetedMS
Dependencies should now be declared in the module's build.gradle. See the TargetedMS module's copy for an example

2020-03-26 16:00 UTC, labkey-jeckels requested changes
@labkey-tchad made a good point that we should make the module name more specific here. Can you change the parent directory from "dashboard" to "panoramawebdashboard" or similar, since all module names share a global scope? Thanks!

2020-03-26 18:39 UTC, labkey-jeckels commented
Renaming the Java package and other similar scoping makes sense too to help avoid future conflicts

2020-03-27 16:07 UTC, vagisha commented
Created new PR with requested changes: https://github.com/LabKey/MacCossLabModules/pull/38

2020-03-27 16:07 UTC, closed without merging