Issue 1713: Suppress trailing ? in URL strings if no parameters
LabKey/MacCossLabModules pull request #96
Opened 2020-12-03 09:56 UTC by labkey-kevink

#### Rationale
With the experimental no-question-mark-url flag enabled, it isn't safe to concatenate parameters to the end of a URL.

#### Related Pull Requests
- https://github.com/LabKey/platform/pull/1603

#### Changes
- don't use string concatenation to add parameters to URLs

2020-12-10 21:54 UTC, labkey-adam commented
Should we introduce a new `JspBase.jsUrl()` method to simplify this pattern? I'm thinking:

```<%=jsUrl(new ActionURL(ShowRunAction.class, c))%>```

instead of

```new URL(<%=q(new ActionURL(ShowRunAction.class, c).getURIString())%>)```

This continues the theme of using ActionURL as much as possible, reducing the number of `getURIString()` references to check/annotate.

2020-12-10 21:54 UTC, labkey-adam requested changes
Couple things to consider

2020-12-10 21:54 UTC, labkey-adam commented on testresults/src/org/labkey/testresults/view/longTerm.jsp
> +                    failureTableHTML += '<tr><td><a href="' + url.toString() + '">'+failure[0]+'</a></td><td>'+failure[1]+'</td></tr>';
HTML encode url and failures?

2021-02-13 14:21 UTC, labkey-kevink commented on testresults/src/org/labkey/testresults/view/longTerm.jsp
> +                    failureTableHTML += '<tr><td><a href="' + url.toString() + '">'+failure[0]+'</a></td><td>'+failure[1]+'</td></tr>';
Fixed

2021-02-13 14:24 UTC, labkey-kevink commented
I added the `jsURL()` method and it works, but IntelliJ doesn't give good code completion for the local url variable when we do this.  We can add a local type annotation to the block, but it gets a little ugly:

```
/** @type URL */
var url = <%=jsURL(new ActionURL(...))%>;
// IntelliJ can code complete the properties on the url variable now
```

2021-02-15 01:19 UTC, labkey-adam commented
Looks okay to me. Most (all?) of these could be simplified by using `urlFor(actionClass)`. Even better... another variant of your new method: `jsUrl(actionClass)`. Optional... but super cool :)

2021-02-15 01:20 UTC, labkey-adam approved these changes

2021-02-15 01:26 UTC, merged